
# World parameters
world:
  world_seed: -1
  petridish_radius: 5.0

# Physics parameters
physics:
  friction: 1.0
  static_friction: 1.0
  physics_substeps: 3
  collision_map_resolution: 10 #per unit of space
  time_step: 1
  iterations_per_tick: 35
  sim_speed: 10

# Graphics parameters
graphics:
