
# World parameters
world:
  world_seed: -1
  petridish_radius: 50.0

# Physics parameters
physics:
  friction: 1.0
  static_friction: 1.0
  physics_substeps: 3
  collision_map_resolution: 10 #per unit of space
  calculations_per_second: 30
